package com.bliblifuture.hrisbackend.constant.enumerator;

public enum RequestType {

    ATTENDANCE, ANNUAL_LEAVE, SPECIAL_LEAVE, EXTRA_LEAVE, SUBSTITUTE_LEAVE, EXTEND_ANNUAL_LEAVE, HOURLY_LEAVE,
    INCOMING_REQUESTS, SET_HOLIDAY, EMPLOYEE,
    LEAVE, EXTEND
}
